import sqlite3 from 'sqlite3';
import { open } from 'sqlite';

async function main() {
    const db = await open({
        filename: './data.sqlite',
        driver: sqlite3.Database
    });

    // Create the new table for storing game information if it doesn't exist
    await db.exec(`
        CREATE TABLE IF NOT EXISTS game_info (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            base_image_url TEXT,
            total_sprites INTEGER,
            total_fusions INTEGER,
            total_custom_fusions INTEGER,
            total_triple_fusions INTEGER,
            total_custom_sprites INTEGER,
            total_artists INTEGER
        )
    `);

    // Get the total number of Pokémon sprites
    const totalSprites = await db.get(`SELECT COUNT(*) AS total FROM sprites`);

    // Get the total number of fusions (head + body sprites like 1.2, 23.43)
    const totalFusionsQuery = `
        SELECT COUNT(*) AS total_fusions
        FROM sprites
        WHERE id LIKE '%.%'
          AND id NOT LIKE '%.%.%'
    `;
    const totalFusions = await db.get(totalFusionsQuery);

    // Get the total number of custom fusions (excluding those generated by Japeal Fusion Generator)
    const totalCustomFusionsQuery = `
        WITH CustomFusions AS (
            SELECT
                id,
                json_extract(primary_image, '$.artist') AS artist
            FROM
                sprites
            WHERE
                id LIKE '%.%'
                AND id NOT LIKE '%.%.%'
                AND NOT EXISTS (
                    SELECT 1
                    FROM json_each(json_extract(primary_image, '$.artist')) AS a
                    WHERE a.value = 'Japeal Fusion Generator'
                )
        )
        SELECT
            COUNT(*) AS total_custom_fusions
        FROM
            CustomFusions
        WHERE
            artist IS NOT NULL;
    `;
    const totalCustomFusions = await db.get(totalCustomFusionsQuery);

    // Get the total number of triple fusions (like 1.1.1)
    const totalTripleFusionsQuery = `
        SELECT COUNT(*) AS total_triple_fusions
        FROM sprites
        WHERE id LIKE '%.%.%'
    `;
    const totalTripleFusions = await db.get(totalTripleFusionsQuery);

    // Get the total number of custom sprites (excluding those generated by Japeal Fusion Generator)
    const totalCustomSpritesQuery = `
        WITH CustomSprites AS (
            SELECT
                id,
                json_extract(primary_image, '$.artist') AS artist
            FROM
                sprites
            WHERE
                json_extract(primary_image, '$.url') LIKE '%.%'
                AND NOT EXISTS (
                    SELECT 1
                    FROM json_each(json_extract(primary_image, '$.artist')) AS a
                    WHERE a.value = 'Japeal Fusion Generator'
                )
        )
        SELECT
            COUNT(*) AS total_custom_sprites
        FROM
            CustomSprites
        WHERE
            artist IS NOT NULL;
    `;
    const totalCustomSprites = await db.get(totalCustomSpritesQuery);

    // Get the total number of artists
    const totalArtists = await db.get(`SELECT COUNT(*) AS total FROM artists`);

    // Base image URL
    const baseImageUrl = "https://cdn.jsdelivr.net/gh/Vish2007/pif@tree/main";

    // Insert or replace the data into the game_info table
    await db.run(`
        INSERT OR REPLACE INTO game_info (
            id, base_image_url, total_sprites, total_fusions, total_custom_fusions, total_triple_fusions, total_custom_sprites, total_artists
        ) VALUES (
            1, ?, ?, ?, ?, ?, ?, ?
        )
    `, [
        baseImageUrl,
        totalSprites.total,
        totalFusions.total_fusions,
        totalCustomFusions.total_custom_fusions,
        totalTripleFusions.total_triple_fusions,
        totalCustomSprites.total_custom_sprites,
        totalArtists.total
    ]);

    console.log('Game information has been successfully inserted or replaced in the database.');
}

main().catch(err => console.error(err));
